services:
  karser_recaptcha3.form.type:
    class: Karser\Recaptcha3Bundle\Form\Recaptcha3Type
    arguments:
      - '%karser_recaptcha3.site_key%'
      - '%karser_recaptcha3.enabled%'
    tags:
      - { name: form.type, alias: karser_recaptcha3 }

  karser_recaptcha3.validator:
    class:  Karser\Recaptcha3Bundle\Validator\Constraints\Recaptcha3Validator
    arguments:
      - '@karser_recaptcha3.google.recaptcha'
      - '%karser_recaptcha3.enabled%'
      - '@karser_recaptcha3.ip_resolver'
    tags:
      - { name: validator.constraint_validator, alias: karser_recaptcha3_validator }

  karser_recaptcha3.ip_resolver:
    class: Karser\Recaptcha3Bundle\Services\IpResolver
    arguments:
      - '@kernel'

  karser_recaptcha3.google.recaptcha:
    class: 'ReCaptcha\ReCaptcha'
    arguments:
      $secret: '%karser_recaptcha3.secret_key%'
      $requestMethod: '@karser_recaptcha3.google.request_method'
    calls:
      - [setScoreThreshold, ['%karser_recaptcha3.score_threshold%']]

  karser_recaptcha3.google.request_method: '@karser_recaptcha3.google.request_method.curl_post'

  karser_recaptcha3.google.request_method.curl_post:
    class: 'ReCaptcha\RequestMethod\CurlPost'

  karser_recaptcha3.google.request_method.curl:
    class: 'ReCaptcha\RequestMethod\Curl'